version: '3.8'

services:
  nginx-server:
    build:
      context: .
    container_name: servidor-nginx

    volumes:
      - ./dist/html:/usr/share/nginx/html:ro

    ports:
      - 8080:80
      - 8443:443
    

    
